### ISSUE TITLE
Fix UploadFromUrl::initWithUrl method

### ISSUE THREAD

**Issue by ataev-timur** [igogo5yo/yii2-upload-from-url#4]
instead 

return self::getInstance([
        'url' => $url
]);
return self::createInstance([
        'url' => $url
]);

**Comment by igogo5yo** [comment]
Why?
Method UploadFromUrl::getInstance want 2 attributes - $model and $attribute

**Comment by ataev-timur** [comment]
I don't know, but when download packege with composer, in UploadFromUrl class, I even don't have getInstance() method.

**Comment by igogo5yo** [comment]
Holy crap!
I forgot make release with this change.
Try now please!

**Comment by ataev-timur** [comment]
Yes, now works fine.

**Comment by igogo5yo** [comment]
Thanx for this issue!

**Comment by ataev-timur** [comment]
Thanks for package)

2015-10-21 11:23 GMT+03:00 Skliar Ihor notifications@github.com:
