### ISSUE TITLE
copy(uploads/yii.png): failed to open stream: No such file or directory",

### ISSUE THREAD

**Issue by dungphanxuan** [igogo5yo/yii2-upload-from-url#5]
Hi, I have error when upload file from url.
"copy(uploads/yii.png): failed to open stream: No such file or directory",

**Comment by igogo5yo** [comment]
I think you don't have permission for write into directory uploads/
Or you don't have this directory

**Comment by dungphanxuan** [comment]
success, thank for your extendsion. I missing directory

**Comment by igogo5yo** [comment]
You are welcome ;)
