### ISSUE TITLE
Using post parameters

### ISSUE THREAD

**Issue by AntoninSlejska** [igogo5yo/yii2-upload-from-url#6]
Can I use post parameters, when I define the URL?

I need to automatically save exported CSV files, see: http://stackoverflow.com/questions/36301480/yii2-how-to-start-an-export-programmatically

So I need something like:

```
$url = 'controller/action' ;
$post_params = [
     'key1' => 'value1',
     'key2' => 'value2'
];
$path = 'uploads/yii.png';
$model = new Post();

$file = UploadFromUrl::initWithUrlAndModel($url, $model, 'image', $post_params);
$file->saveAs($path, true);
```

**Comment by igogo5yo** [comment]
Sorry, but this is impossible with current version
But you can write a code and send me a pull request and if all will works fine I will release new version!

**Comment by AntoninSlejska** [comment]
OK, I will try it. Thanks!
